version: '3.8'

services:
  flask-app:
    build: .
    container_name: flask-app
    ports:
      - "5000:5000"
    depends_on:
      - mysql-db
    environment:
      - FLASK_APP=app.py
      - ENCRYPTION_KEY=CCbTLCkE3XcX-dUUoV1RcXNJiBchflFe1ROvnELcVJ8=
      - DB_USER=root
      - DB_PASSWORD=root
      - DB_HOST=mysql-db  # Use the service name for Docker networking
      - DB_NAME=event_bookings
    volumes:
      - .:/app
    networks:
      - app-network

  mysql-db:
    image: mysql:8.0
    container_name: mysql-db
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: event_bookings
    volumes:
      - "./database_setup/sql_setup:/docker-entrypoint-initdb.d"
    ports:
      - "3306:3306"
    networks:
      - app-network

networks:
  app-network:
    driver: bridge
